GET http://localhost:8080/hello/alaynna

###

POST http://localhost:8080/login
content-type: application/json

{"username":"alaynna2",
"password":"boo"}

###

GET http://localhost:8080/getUser

###

POST http://localhost:8080/user
content-type: application/json

{"username":"alaynna2",
"password":"boo"}

###

DELETE http://localhost:8080/logout

###

POST http://localhost:8080/posts
content-type: application/json

{
  "authorId": "alaynna2",
  "content": "Hello, world!",
  "imageUrl": ""
}

###

GET http://localhost:8080/posts

###

GET http://localhost:8080/posts/user/alaynna2